apiVersion: apps/v1
kind: Deployment
metadata:
  name: insight
  namespace: insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insight
      version: "1.0"
  template:
    metadata:
      labels:
        app: insight
        version: "1.0"
    spec:
      initContainers:
        - name: init-ds
          image: 192.168.65.5:8094/busybox
          command:
            - '/bin/sh'
            - '-c'
            - |
                while true
                do
                  rt=$(nc -z -w 1 insight-postgresql 5432)
                  if [ $? -eq 0 ]; then
                    echo "DB is UP"
                    break
                  fi
                  echo "DB is not yet reachable;sleep for 10s before retry"
                  sleep 10
                done
      containers:
      - name: insight-app
        image: 192.168.65.5:8094/insight
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://insight-postgresql.insight.svc.cluster.local:5432/insight
        - name: SPRING_PROFILES_ACTIVE 
          value: prod,swagger 
        - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES
          value: insight-elasticsearch.insight.svc.cluster.local:9300
        - name: SPRING_DATA_ELASTICSEARCH_CLUSTER_NAME
          value: insight
        - name: SPRING_DATA_JEST_URI 
          value: insight-elasticsearch.insight.svc.cluster.local:9200
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
          value: jhipster-kafka.insight.svc.cluster.local
        - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
          value: jhipster-zookeeper.insight.svc.cluster.local
        - name: JHIPSTER_METRICS_LOGS_ENABLED
          value: 'true'
        - name: JHIPSTER_LOGGING_LOGSTASH_ENABLED
          value: 'true'
        - name: JHIPSTER_LOGGING_LOGSTASH_HOST
          value: jhipster-logstash
        - name: APPLICATION_KIBANA_URI 
          value: http://insight-kibana.insight.svc.cluster.local:5601 
        - name: JAVA_OPTS
          value: " -Xmx2048m -Xms256m"
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /management/health
            port: http
          initialDelaySeconds: 120
