apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: refgeo-elasticsearch
  namespace: refgeo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: refgeo-elasticsearch
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: elasticsearch
        image: 192.168.65.5:8093/elasticsearch:gazetter
        env:
        - name: ES_JAVA_OPTS
          value: -Xmx256m -Xms256m
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data/
---
apiVersion: v1
kind: Service
metadata:
  name: refgeo-elasticsearch
  namespace: refgeo
spec:
  selector:
    app: refgeo-elasticsearch
  ports:
  - port: 9200
    name: http
    protocol: TCP
    nodePort: 32000
  - port: 9300
    name: transport
    protocol: TCP
  type: NodePort