apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-ner-kaf2json
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-ner-kaf2json
    spec:
      containers:
      - image: cwolff/opener-docker-kaf2json
        name: insight-ner-kaf2json
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: insight-ner-kaf2json
  namespace: insight
  labels:
    app: insight-ner-kaf2json
spec:
  ports:
  - name: http
    port: 85
    targetPort: 80
  selector:
    app: insight-ner-kaf2json
---