apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-nifi
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-nifi
    spec:
      containers:
      - name: nifi 
        image: apache/nifi:latest
        ports:
        - containerPort: 8080
          name: front
          protocol: TCP 
        - containerPort: 10514
          name: listener
          protocol: UDP 
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
          limits:
            memory: "2048Mi"
            cpu: "1"
        volumeMounts:
        - name: storage
          mountPath: /opt/nifi/nifi-current/conf/templates/
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: insight-storage-nifi-claim
---
apiVersion: v1
kind: Service
metadata:
  name: insight-nifi
  namespace: insight
spec:
  selector:
    app: insight-nifi
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: udp 
    port: 10514 
    targetPort: 10514 
