version: '2'
services:
    insight-app:
        image: insight
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://insight-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=insight
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://insight-elasticsearch:9200
        ports:
            - 8080:8080
    insight-mongodb:
        extends:
            file: mongodb.yml
            service: insight-mongodb
    insight-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: insight-elasticsearch
