version: '2'
services:
    insight-mongodb:
        image: mongo:4.0.2
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/insight/mongodb/:/data/db/
        networks:
            - insight
networks:
    insight:
        external: true
