version: '2'
services:
    insight-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/insight/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=insight
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
