apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-kibana
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-kibana
    spec:
      imagePullSecrets:
      - name: regcred
      initContainers:
      - name: init-ds
        image: 192.168.0.52:9082/busybox
        command:
        - '/bin/sh'
        - '-c'
        - |
            while true
            do
              rt=$(nc -z -w 1 insight-elasticsearch 9200)
              if [ $? -eq 0 ]; then
                echo "ELASTIC is UP"
                break
              fi
              echo "ELASTIC is not yet reachable;sleep for 10s before retry"
              sleep 10
            done

      containers:
      - image: 192.168.0.52:9082/kibana/kibana-oss:6.4.2
        env:
        - name: server.name
          value: insight-kibana
        - name: server.host
          value: "0"
        - name: ELASTICSEARCH_URL 
          value: http://insight-elasticsearch.insight.svc.cluster.local:9200
        name: insight-kibana
        ports:
        - containerPort: 5601
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: insight-kibana
  namespace: insight
  labels:
    app: insight-kibana
spec:
  ports:
  - name: http
    port: 5601
    nodePort: 30100 
    targetPort: 5601
  type: NodePort
  selector:
    app: insight-kibana
---
