apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-elasticsearch
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-elasticsearch
    spec:
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: data
        persistentVolumeClaim:
            claimName: insight-storage-elasticsearch-claim
      initContainers:
      - name: init-sysctl
        image: 192.168.0.52:9082/busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: 192.168.0.52:9082/elasticsearch/elasticsearch-oss:6.4.2
        env:
        - name: cluster.name
          value: insight
        - name: discovery.zen.minimum_master_nodes
          value: "1"
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data/

---
apiVersion: v1
kind: Service
metadata:
  name: insight-elasticsearch
  namespace: insight
spec:
  selector:
    app: insight-elasticsearch
  ports:
  - port: 9200
    name: http
    protocol: TCP
  - port: 9300
    name: transport
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: insight-node-elasticsearch
  namespace: insight
spec:
  selector:
    app: insight-elasticsearch
  ports:
  - port: 9200
    name: http
    protocol: TCP
    nodePort: 30201
  type: NodePort
