apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-janusgraph
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-janusgraph
    spec:
      containers:
      - name: janusgraph 
        image: peploleum/janusgraph:1.0.0
        ports:
        - containerPort: 8182
          name: gremlin
          protocol: TCP 
        - containerPort: 9160
          name: cassandra
          protocol: TCP
        - containerPort: 9042
          name: janus
          protocol: TCP
        command: ["/bin/sh", "-c", "set -e; set -x; cp ./log/gremlin-server-configuration.yaml ./conf/gremlin-server/ && cp ./log/startup.groovy /app/janusgraph-0.2.2-hadoop2/scripts/ && cp ./log/janusgraph.properties /app/janusgraph-0.2.2-hadoop2/conf/ && ./bin/gremlin-server.sh ./conf/gremlin-server/gremlin-server-configuration.yaml"]
        resources:
          requests:
            memory: "4096Mi"
            cpu: "1"
          limits:
            memory: "4096Mi"
            cpu: "1"
        volumeMounts:
        - name: storage
          mountPath: /app/janusgraph-0.2.2-hadoop2/log
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: insight-storage-graph-claim 
---
apiVersion: v1
kind: Service
metadata:
  name: insight-janusgraph
  namespace: insight
spec:
  selector:
    app: insight-janusgraph
  type: NodePort
  ports:
  - name: janus
    port: 9042
    targetPort: 9042
  - name: cassandra 
    port: 9160 
    targetPort: 9160 
  - name: gremlin
    port: 8182
    targetPort: 8182
