apiVersion: v1
kind: PersistentVolume
metadata:
  name: insight-storage-master-data
  namespace: insight
  labels:
    component: insight-console-es-master-volume
    role: data
    type: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage 
  local:
    path: /tmp/kubernetes/INSIGHT/master
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernetes-node
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: insight-storage-data-data
  namespace: insight
  labels:
    component: insight-console-es-data-volume
    role: data
    type: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage 
  local:
    path: /tmp/kubernetes/INSIGHT/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernetes-node
