apiVersion: v1
kind: PersistentVolume
metadata:
  name: insight-storage-graph-data
  namespace: insight
  labels:
    component: insight-graph-volume
    role: data
    type: local
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage 
  local:
    path: /home/capgemini/binding/INSIGHT/graph/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernetes-node2
---
