kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: insight-storage-cassandra-claim
  namespace: insight
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      component: insight-cassandra-volume
---
