apiVersion: v1
kind: PersistentVolume
metadata:
  name: refgeo-storage-logstash-data
  namespace: insight
  labels:
    component: refgeo-logstash-volume
    role: data
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage 
  local:
    path: /home/capgemini/binding/INSIGHT/refgeo/logstash/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubernetes-node-01
---
