apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: insight
data:
    kafka.create.topics: topic:1:1,topicrss:1:1,topicjson:1:1 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-kafka
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:latest
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: insight-kafka.insight.svc.cluster.local
        - name: KAFKA_ADVERTISED_PORT
          value: '9092'
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: insight-zookeeper.insight.svc.cluster.local:2181
        - name: KAFKA_CREATE_TOPICS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: 'kafka.create.topics'
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: insight-kafka
  namespace: insight
spec:
  selector:
    app: insight-kafka
  ports:
  - port: 9092
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-zookeeper
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper:latest
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: insight-zookeeper
  namespace: insight
spec:
  selector:
    app: insight-zookeeper
  ports:
  - port: 2181
