apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-config
  namespace: insight
data:
    syslog.server.host: insight-rsyslog-server 
    syslog.server.port: "514"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: insight-rsyslog-client
  namespace: insight
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insight-rsyslog-client
    spec:
     containers:
      - name: rsyslogclient
        image: 192.168.65.5:8094/rsyslog/client:latest
        ports:
        - containerPort: 23 
        resources:
          requests:
            memory: "256Mi"
            cpu: "1"
          limits:
            memory: "256Mi"
            cpu: "1"
        env:
        - name: SYSLOG_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: syslog-config
              key: syslog.server.host
        - name: SYSLOG_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: syslog-config
              key: syslog.server.port
---
apiVersion: v1
kind: Service
metadata:
  name: insight-rsyslog-client
  namespace: insight
spec:
  selector:
    app: insight-rsyslog-client
  type: NodePort
  ports:
  - name: tcp 
    port: 23 
    targetPort: 23
